  - name: Debug repository contents
    run: |
      echo "Commit used by runner: $(git rev-parse HEAD)"
      echo "Current ref: ${GITHUB_REF}"
      echo "Workspace: ${GITHUB_WORKSPACE}"
      echo "List referate dir:"
      ls -la "${GITHUB_WORKSPACE}/referate" || true
      echo "Tracked files matching 'Referat_Metode':"
      git ls-tree -r --name-only HEAD | grep -i 'Referat_Metode' || true
      echo "Exact filenames with quoting:"
      git ls-files -z | xargs -0 -n1 printf '%q\n' | grep 'Referat_Metode' || true
      if [ ! -f "${GITHUB_WORKSPACE}/${INPUT_MD}" ]; then
        echo "::error::Input file not found at ${GITHUB_WORKSPACE}/${INPUT_MD}"
        exit 1
      fi

  - name: Install pandoc
    run: |
      sudo apt-get update
      sudo apt-get install -y pandoc

  - name: Convert Markdown to DOCX
    run: |
      pandoc -s "${GITHUB_WORKSPACE}/${INPUT_MD}" \
        -o "${GITHUB_WORKSPACE}/${OUTPUT_DOCX}" \
        --metadata=title:"Metode de recondiționare. Prelucrări mecanice" \
        --metadata=author:"Ungureanu Victor"

  - name: Commit DOCX back to repository
    uses: stefanzweifel/git-auto-commit-action@v5
    with:
      commit_message: "Build DOCX: ${{ env.OUTPUT_DOCX }}"
      file_pattern: ${{ env.OUTPUT_DOCX }}
